### ISSUE TITLE
List of all packages that needs to be installed 

### ISSUE THREAD

**Issue by thokall** [NBISweden/RaukR#2]
Instead of stating that the full list of need packages are listed at the top of the example files, I would list them explicitly in the readme eg:

```install.packages(c("kableExtra", "formattable", "DT", "highcharter", "plotly", "ggiraph", "dygraphs", "networkD3", "leaflet", "crosstalk", "tidyverse", ))```

**Comment by royfrancis** [comment]
@thokall Thanks! Will add that to the README.

We could have added them as dependencies to the package, but it seems unnecessary to force everyone to install all these packages if they are not going to use these widgets.

**Comment by thokall** [comment]
I agree that it is better to list them. I was just testing to knit the example without checking that I had all the packages and as there are quite a few it is nice to give a full install instruction.

**Comment by royfrancis** [comment]
Added to README.md in v1.0.1.
